export interface CodeSnippet {
  cpp: string[]
  python: string[]
  typescript: string[]
  java: string[]
}

export const codeSnippets: Record<string, CodeSnippet> = {
  "singly-insertAt": {
    cpp: [
      "void insertAt(Node*& head, int index, int val) {",
      "    Node* newNode = new Node(val);",
      "    if (index == 0) {",
      "        newNode->next = head;",
      "        head = newNode;",
      "        return;",
      "    }",
      "    Node* curr = head;",
      "    for (int i = 0; i < index - 1 && curr != nullptr; ++i) {",
      "        curr = curr->next;",
      "    }",
      "    if (curr == nullptr) return; // Out of bounds",
      "    newNode->next = curr->next;",
      "    curr->next = newNode;",
      "}",
    ],
    python: [
      "def insert_at(head, index, val):",
      "    new_node = ListNode(val)",
      "    if index == 0:",
      "        new_node.next = head",
      "        return new_node",
      "    ",
      "    curr = head",
      "    for i in range(index - 1):",
      "        if not curr: return head",
      "        curr = curr.next",
      "    ",
      "    new_node.next = curr.next",
      "    curr.next = new_node",
      "    return head",
    ],
    typescript: [
      "function insertAt(head: ListNode | null, index: number, val: number): ListNode {",
      "  const newNode = new ListNode(val);",
      "  if (index === 0) {",
      "    newNode.next = head;",
      "    return newNode;",
      "  }",
      "  let curr = head;",
      "  for (let i = 0; i < index - 1 && curr !== null; i++) {",
      "    curr = curr.next;",
      "  }",
      "  if (!curr) return head;",
      "  newNode.next = curr.next;",
      "  curr.next = newNode;",
      "  return head;",
      "}",
    ],
    java: [
      "public ListNode insertAt(ListNode head, int index, int val) {",
      "    ListNode newNode = new ListNode(val);",
      "    if (index == 0) {",
      "        newNode.next = head;",
      "        return newNode;",
      "    }",
      "    ListNode curr = head;",
      "    for (int i = 0; i < index - 1 && curr != null; i++) {",
      "        curr = curr.next;",
      "    }",
      "    if (curr == null) return head;",
      "    newNode.next = curr.next;",
      "    curr.next = newNode;",
      "    return head;",
      "}",
    ],
  },
  "singly-deleteAt": {
    cpp: [
      "void deleteAt(Node*& head, int index) {",
      "    if (head == nullptr) return;",
      "    if (index == 0) {",
      "        Node* toDelete = head;",
      "        head = head->next;",
      "        delete toDelete;",
      "        return;",
      "    }",
      "    Node* curr = head;",
      "    for (int i = 0; i < index - 1 && curr->next != nullptr; ++i) {",
      "        curr = curr->next;",
      "    }",
      "    if (curr->next == nullptr) return;",
      "    Node* toDelete = curr->next;",
      "    curr->next = toDelete->next;",
      "    delete toDelete;",
      "}",
    ],
    python: [
      "def delete_at(head, index):",
      "    if not head: return None",
      "    if index == 0:",
      "        to_delete = head",
      "        return head.next",
      "    ",
      "    curr = head",
      "    for i in range(index - 1):",
      "        if not curr.next: return head",
      "        curr = curr.next",
      "    ",
      "    if not curr.next: return head",
      "    to_delete = curr.next",
      "    curr.next = to_delete.next",
      "    return head",
    ],
    typescript: [
      "function deleteAt(head: ListNode | null, index: number): ListNode | null {",
      "  if (!head) return null;",
      "  if (index === 0) {",
      "    return head.next;",
      "  }",
      "  let curr = head;",
      "  for (let i = 0; i < index - 1 && curr.next !== null; i++) {",
      "    curr = curr.next;",
      "  }",
      "  if (!curr.next) return head;",
      "  const toDelete = curr.next;",
      "  curr.next = toDelete.next;",
      "  return head;",
      "}",
    ],
    java: [
      "public ListNode deleteAt(ListNode head, int index) {",
      "    if (head == null) return null;",
      "    if (index == 0) return head.next;",
      "    ListNode curr = head;",
      "    for (int i = 0; i < index - 1 && curr.next != null; i++) {",
      "        curr = curr.next;",
      "    }",
      "    if (curr.next == null) return head;",
      "    ListNode toDelete = curr.next;",
      "    curr.next = toDelete.next;",
      "    return head;",
      "}",
    ],
  },
  "doubly-insertAt": {
    cpp: [
      "void insertAtDoubly(DNode*& head, int index, int val) {",
      "    DNode* newNode = new DNode(val);",
      "    if (index == 0) {",
      "        newNode->next = head;",
      "        if (head) head->prev = newNode;",
      "        head = newNode;",
      "        return;",
      "    }",
      "    DNode* curr = head;",
      "    for (int i = 0; i < index - 1 && curr->next != nullptr; ++i) {",
      "        curr = curr->next;",
      "    }",
      "    newNode->next = curr->next;",
      "    newNode->prev = curr;",
      "    if (curr->next) curr->next->prev = newNode;",
      "    curr->next = newNode;",
      "}",
    ],
    python: [
      "def insert_at_doubly(head, index, val):",
      "    new_node = DNode(val)",
      "    if index == 0:",
      "        new_node.next = head",
      "        if head: head.prev = new_node",
      "        return new_node",
      "    curr = head",
      "    for i in range(index - 1):",
      "        if not curr.next: break",
      "        curr = curr.next",
      "    new_node.next = curr.next",
      "    new_node.prev = curr",
      "    if curr.next: curr.next.prev = new_node",
      "    curr.next = new_node",
      "    return head",
    ],
    typescript: [
      "function insertAtDoubly(head: DNode | null, index: number, val: number): DNode {",
      "  const newNode = new DNode(val);",
      "  if (index === 0) {",
      "    newNode.next = head;",
      "    if (head) head.prev = newNode;",
      "    return newNode;",
      "  }",
      "  let curr = head;",
      "  for (let i = 0; i < index - 1 && curr?.next; i++) {",
      "    curr = curr.next;",
      "  }",
      "  newNode.next = curr!.next;",
      "  newNode.prev = curr;",
      "  if (curr!.next) curr!.next.prev = newNode;",
      "  curr!.next = newNode;",
      "  return head!;",
      "}",
    ],
    java: [
      "public DNode insertAt(DNode head, int index, int val) {",
      "    DNode newNode = new DNode(val);",
      "    if (index == 0) {",
      "        newNode.next = head;",
      "        if (head != null) head.prev = newNode;",
      "        return newNode;",
      "    }",
      "    DNode curr = head;",
      "    for (int i = 0; i < index - 1 && curr.next != null; i++) {",
      "        curr = curr.next;",
      "    }",
      "    newNode.next = curr.next;",
      "    newNode.prev = curr;",
      "    if (curr.next != null) curr.next.prev = newNode;",
      "    curr.next = newNode;",
      "    return head;",
      "}",
    ],
  },
  "circular-insertAt": {
    cpp: [
      "void insertAtCircular(CNode*& head, int index, int val) {",
      "    CNode* newNode = new CNode(val);",
      "    if (!head) {",
      "        newNode->next = newNode;",
      "        head = newNode;",
      "        return;",
      "    }",
      "    if (index == 0) {",
      "        CNode* tail = head;",
      "        while (tail->next != head) tail = tail->next;",
      "        newNode->next = head;",
      "        tail->next = newNode;",
      "        head = newNode;",
      "        return;",
      "    }",
      "    CNode* curr = head;",
      "    for (int i = 0; i < index - 1; ++i) {",
      "        curr = curr->next;",
      "        if (curr == head) break;",
      "    }",
      "    newNode->next = curr->next;",
      "    curr->next = newNode;",
      "}",
    ],
    python: [
      "def insert_at_circular(head, index, val):",
      "    new_node = Node(val)",
      "    if not head:",
      "        new_node.next = new_node",
      "        return new_node",
      "    if index == 0:",
      "        tail = head",
      "        while tail.next != head:",
      "            tail = tail.next",
      "        new_node.next = head",
      "        tail.next = new_node",
      "        return new_node",
      "    curr = head",
      "    for _ in range(index - 1):",
      "        curr = curr.next",
      "        if curr == head: break",
      "    new_node.next = curr.next",
      "    curr.next = new_node",
      "    return head",
    ],
    typescript: [
      "function insertAtCircular(head: Node | null, index: number, val: number): Node {",
      "  const newNode = new Node(val);",
      "  if (!head) {",
      "    newNode.next = newNode;",
      "    return newNode;",
      "  }",
      "  if (index === 0) {",
      "    let tail = head;",
      "    while (tail.next !== head) tail = tail.next;",
      "    newNode.next = head;",
      "    tail.next = newNode;",
      "    return newNode;",
      "  }",
      "  let curr = head;",
      "  for (let i = 0; i < index - 1 && curr.next !== head; i++) {",
      "    curr = curr.next;",
      "  }",
      "  newNode.next = curr.next;",
      "  curr.next = newNode;",
      "  return head;",
      "}",
    ],
    java: [
      "public Node insertAtCircular(Node head, int index, int val) {",
      "    Node newNode = new Node(val);",
      "    if (head == null) {",
      "        newNode.next = newNode;",
      "        return newNode;",
      "    }",
      "    if (index == 0) {",
      "        Node tail = head;",
      "        while (tail.next != head) tail = tail.next;",
      "        newNode.next = head;",
      "        tail.next = newNode;",
      "        return newNode;",
      "    }",
      "    Node curr = head;",
      "    for (int i = 0; i < index - 1 && curr.next != head; i++) {",
      "        curr = curr.next;",
      "    }",
      "    newNode.next = curr.next;",
      "    curr.next = newNode;",
      "    return head;",
      "}",
    ],
  },
}
